# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build gauss-rest with Maven
      run: mvn -B package --file rest/pom.xml
    - name: Make chromedriver executable
      run: chmod +x test/chromedriver
    - name: Run JAR and tests
      run: |
           java -jar rest/target/gauss-rest-1.5.3.RELEASE.jar &
           sleep 5
           mvn clean test --file test/pom.xml
